### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by jcs090218** [emacs-helm/helm-searcher#2]
@thierryvolpiatto hmm.. It seems like I no longer have the push permission to this repository. 😕 

```
remote: Permission to emacs-helm/helm-searcher.git denied to jcs090218.
fatal: unable to access 'https://github.com/emacs-helm/helm-searcher.git/': The requested URL returned error: 403
```

**Comment by thierryvolpiatto** [comment]
Jen-Chieh Shen <notifications@github.com> writes:

> @thierryvolpiatto hmm.. It seems like I no longer have the push permission to this repository. 😕

Yes you had only read access to the repo don't know why, I wonder how
you could create it, never mind now you should have full access (I set
you to admin), let me know if you still unable to write or anything
else.

-- 
Thierry

**Comment by jcs090218** [comment]
> Yes you had only read access to the repo don't know why, I wonder how
you could create it, never mind now you should have full access (I set
you to admin), let me know if you still unable to write or anything
else.

Thank you! Now it works! ;)
